import Head from "next/head";

import styles from "@/styles/Home.module.css";
import Layout from "@/components/Layout";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout data={data} />
    </>
  );
}

export const getStaticProps = async (context) => {
  const data = await fetch("http://localhost:3000/api/test").then((res) =>
    res.json()
  );
  console.log(data);
  return {
    props: {
      data,
    },
  };
};
